package com.example.application.fullcalendar.entryprovider;

import com.example.application.fullcalendar.model.Entry;
import com.vaadin.flow.function.SerializableConsumer;
import com.vaadin.flow.shared.Registration;

import java.util.*;
import java.util.function.Consumer;

/**
 * Abstract base implementation of the {@link EntryProvider} interface.
 * @author Stefan Uebe
 */
public abstract class AbstractEntryProvider<T extends Entry> implements EntryProvider<T> {

    private final Map<Class<?>, List<SerializableConsumer<?>>> listeners = new HashMap<>();

    @Override
    public void refreshAll() {
        fireEvent(new EntriesChangeEvent<>(this));
    }

    @Override
    public void refreshItem(T item) {
        fireEvent(new EntryRefreshEvent<>(this, item));
    }

    /**
     * Registers a new listener with the specified activation method to listen
     * events generated by this component. If the activation method does not
     * have any arguments the event object will not be passed to it when it's
     * called.
     *
     * @param eventType the type of the listened event. Events of this type or its
     *                  subclasses activate the listener.
     * @param method    the consumer to receive the event.
     * @param <E>       the event type
     * @return a registration for the listener
     */
    protected <E> Registration addListener(Class<E> eventType, SerializableConsumer<E> method) {
        List<SerializableConsumer<?>> list = listeners.computeIfAbsent(eventType, key -> new ArrayList<>());

        return Registration.addAndRemove(list, method);
    }

    @Override
    public Registration addEntriesChangeListener(EntriesChangeEvent.EntriesChangeListener<T> listener) {
        return addListener(EntriesChangeEvent.class, listener::onDataChange);
    }

    @Override
    public Registration addEntryRefreshListener(EntryRefreshEvent.EntryRefreshListener<T> listener) {
        return addListener(EntryRefreshEvent.class, listener::onDataRefresh);
    }

    /**
     * Sends the event to all listeners.
     *
     * @param event the Event to be sent to all listeners.
     */
    @SuppressWarnings({"unchecked", "rawtypes"})
    protected void fireEvent(EventObject event) {
        listeners.entrySet().stream()
                .filter(entry -> entry.getKey().isAssignableFrom(event.getClass()))
                .forEach(entry -> {
                    for (Consumer consumer : entry.getValue()) {
                        consumer.accept(event);
                    }
                });
    }
}
