name: Verify
on:
  push:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
jobs:
  verify:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      # for EnricoMi/publish-unit-test-result-action
      issues: read
      checks: write
      pull-requests: write 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Verify
        run: |
          mvn -B -V -ntp verify -Pit,production